---
apiVersion: v1
kind: Service
metadata:
  annotations:
    jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/web-fabric8
    jkube.io/scm-tag: HEAD
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: web-fabric8
    provider: jkube
    version: 0.0.1-SNAPSHOT
    group: code.seven.test
  name: web-fabric8
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-fabric8
    provider: jkube
    group: code.seven.test
